import type { ColunaDefinicao } from "./tipos";

/**
 * Catálogo completo de colunas disponíveis para personalização da tabela
 * de Campanhas (idêntico ao conjunto do Cakto / UTMify).
 */
export const TODAS_AS_COLUNAS: ColunaDefinicao[] = [
  // Geral & Identificação
  {
    id: "tipo",
    rotulo: "Tipo",
    descricao: "Estratégia de orçamento (ex: CBO, ABO, Search, PMax)",
    categoria: "geral",
    padraoAtiva: true,
    formato: "texto",
  },
  {
    id: "orcamento",
    rotulo: "Orçamento",
    descricao: "Orçamento diário programado no gerenciador",
    categoria: "financeiro",
    padraoAtiva: true,
    formato: "moeda",
  },
  {
    id: "custo_produto",
    rotulo: "Custos de Produto",
    descricao: "Custo total do fornecedor (COGS) dos itens vendidos",
    categoria: "financeiro",
    padraoAtiva: false,
    formato: "moeda",
  },
  {
    id: "cpa_desejado",
    rotulo: "CPA desejado",
    descricao: "Meta de custo por aquisição estipulada para a campanha",
    categoria: "conversao",
    padraoAtiva: true,
    formato: "moeda",
  },
  {
    id: "cpt",
    rotulo: "[CPT] - Custo por vendas totais",
    descricao: "Gasto total dividido pelas vendas totais (incluindo pendentes)",
    categoria: "conversao",
    padraoAtiva: false,
    formato: "moeda",
  },
  {
    id: "cpp",
    rotulo: "[CPP] - Custo por vendas pendentes",
    descricao: "Gasto dividido pelas vendas ainda pendentes de pagamento",
    categoria: "conversao",
    padraoAtiva: false,
    formato: "moeda",
  },
  {
    id: "cpa",
    rotulo: "CPA",
    descricao: "Custo por Aquisição (Gasto / Vendas Aprovadas)",
    categoria: "conversao",
    padraoAtiva: true,
    formato: "moeda",
  },
  {
    id: "vendas_totais",
    rotulo: "Vendas Totais",
    descricao: "Total de pedidos gerados (aprovados + pendentes)",
    categoria: "conversao",
    padraoAtiva: false,
    formato: "numero",
  },
  {
    id: "vendas_pendentes",
    rotulo: "Vendas Pendentes",
    descricao: "Pedidos gerados com pagamento aguardando aprovação (Boleto/Pix)",
    categoria: "conversao",
    padraoAtiva: false,
    formato: "numero",
  },
  {
    id: "vendas",
    rotulo: "Vendas",
    descricao: "Total de compras pagas e aprovadas",
    categoria: "conversao",
    padraoAtiva: true,
    formato: "numero",
  },
  {
    id: "gastos",
    rotulo: "Gastos",
    descricao: "Valor consumido em anúncios no período",
    categoria: "financeiro",
    padraoAtiva: true,
    formato: "moeda",
  },
  {
    id: "faturamento",
    rotulo: "Faturamento",
    descricao: "Receita bruta gerada pelas vendas aprovadas",
    categoria: "financeiro",
    padraoAtiva: true,
    formato: "moeda",
  },
  {
    id: "lucro",
    rotulo: "Lucro",
    descricao: "Lucro líquido real (Faturamento - Custo de Produto - Gastos de Anúncio)",
    categoria: "financeiro",
    padraoAtiva: true,
    formato: "moeda",
  },
  {
    id: "roas",
    rotulo: "ROAS",
    descricao: "Retorno sobre o gasto com anúncios (Faturamento / Gastos)",
    categoria: "financeiro",
    padraoAtiva: true,
    formato: "numero",
  },
  {
    id: "margem",
    rotulo: "Margem",
    descricao: "Margem de lucro líquida em percentual (Lucro / Faturamento)",
    categoria: "financeiro",
    padraoAtiva: true,
    formato: "porcentagem",
  },
  {
    id: "roi",
    rotulo: "ROI",
    descricao: "Retorno sobre o investimento total (Lucro / (Gastos + Custo Produto))",
    categoria: "financeiro",
    padraoAtiva: true,
    formato: "porcentagem",
  },
  {
    id: "cpc",
    rotulo: "[CPC] - Custo por clique",
    descricao: "Custo médio pago por clique no anúncio",
    categoria: "trafego",
    padraoAtiva: true,
    formato: "moeda",
  },
  {
    id: "impressoes",
    rotulo: "Impressões",
    descricao: "Número de vezes que os anúncios foram exibidos",
    categoria: "trafego",
    padraoAtiva: false,
    formato: "numero",
  },
  {
    id: "cliques",
    rotulo: "Cliques",
    descricao: "Número de cliques no link do anúncio",
    categoria: "trafego",
    padraoAtiva: true,
    formato: "numero",
  },
  {
    id: "ctr",
    rotulo: "CTR (%)",
    descricao: "Taxa de cliques por impressão (Cliques / Impressões)",
    categoria: "trafego",
    padraoAtiva: false,
    formato: "porcentagem",
  },
  {
    id: "cpm",
    rotulo: "CPM",
    descricao: "Custo por mil impressões",
    categoria: "trafego",
    padraoAtiva: false,
    formato: "moeda",
  },
  {
    id: "ic",
    rotulo: "[IC] - Finalização de compra iniciada",
    descricao: "Quantidade de checkouts iniciados",
    categoria: "conversao",
    padraoAtiva: false,
    formato: "numero",
  },
  {
    id: "cpi",
    rotulo: "[CPI] - Custo por finalização de compra iniciada",
    descricao: "Gasto dividido pela quantidade de checkouts iniciados",
    categoria: "conversao",
    padraoAtiva: false,
    formato: "moeda",
  },
  {
    id: "vis_video",
    rotulo: "[Vis. Vídeo] - Visualizações de Vídeo",
    descricao: "Total de visualizações de reprodução do vídeo",
    categoria: "video",
    padraoAtiva: false,
    formato: "numero",
  },
  {
    id: "vis_3s",
    rotulo: "[Vis. 3 seg] - Vídeos assistidos 3 seg",
    descricao: "Visualizações do vídeo por pelo menos 3 segundos",
    categoria: "video",
    padraoAtiva: false,
    formato: "numero",
  },
  {
    id: "retencao_75",
    rotulo: "[Retenção de Vídeo (75%)]",
    descricao: "Taxa de retenção até 75% do vídeo",
    categoria: "video",
    padraoAtiva: false,
    formato: "porcentagem",
  },
  {
    id: "hook_rate",
    rotulo: "[Hook] - Vídeos assistidos 3 seg / impressões (%)",
    descricao: "Taxa de gancho (quantas pessoas pararam para assistir)",
    categoria: "video",
    padraoAtiva: false,
    formato: "porcentagem",
  },
  {
    id: "hold_rate",
    rotulo: "[Hold Rate] - Vídeos assistidos 75% / impressões (%)",
    descricao: "Taxa de sustentação (quantas pessoas assistiram quase até o fim)",
    categoria: "video",
    padraoAtiva: false,
    formato: "porcentagem",
  },
  {
    id: "frequencia",
    rotulo: "Frequência",
    descricao: "Média de vezes que cada pessoa viu o anúncio",
    categoria: "trafego",
    padraoAtiva: false,
    formato: "numero",
  },
];

export const COLUNAS_PADRAO_IDS = TODAS_AS_COLUNAS
  .filter((c) => c.padraoAtiva)
  .map((c) => c.id);

export const MAPA_COLUNAS = new Map<string, ColunaDefinicao>(
  TODAS_AS_COLUNAS.map((c) => [c.id, c])
);
